
language: csharp

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: trusty
      sudo: required
      mono: 5.4.1
      dotnet: 2.0.0
      cache:
        directories:
          - "$HOME/google-cloud-sdk/"
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
  - curl https://sdk.cloud.google.com | bash;
# Add gcloud to $PATH
  - gcloud version
# Auth flow
  - bash auth-gcloud.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      tags: true