
language: csharp

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.0.0
      nuget: 4.4.1

before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
