
language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
	  mono: none
      dotnet: 2.0.0

before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
