
language: csharp

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: trusty
      sudo: required
      mono: 5.4.1
      dotnet: 2.0.0
cache:
  directories:
      - "$HOME/google-cloud-sdk/"
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
# Auth flow
  - bash auth-gcloud.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      tags: true